-- MySQL Script generated by MySQL Workbench
-- Sun 16 Oct 2016 04:06:16 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portfolio` ;

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`person` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(255) NULL,
  `info_title` VARCHAR(255) NULL,
  `password_digest` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `portfolio`.`person` (`name` ASC);


-- -----------------------------------------------------
-- Table `portfolio`.`person_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`person_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT NOT NULL,
  `position` BIGINT NOT NULL,
  `title` VARCHAR(255) NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `infos_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `portfolio`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idperson_info_UNIQUE` ON `portfolio`.`person_info` (`id` ASC);

CREATE INDEX `person_idx` ON `portfolio`.`person_info` (`person_id` ASC);


-- -----------------------------------------------------
-- Table `portfolio`.`experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`experience` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT NOT NULL,
  `title` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `start` VARCHAR(255) NULL,
  `ending` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `experiences_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `portfolio`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idexperience_UNIQUE` ON `portfolio`.`experience` (`id` ASC);

CREATE INDEX `experiences_person_idx` ON `portfolio`.`experience` (`person_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
